### PR TITLE
Fix the 'on' property result.

### PR DESCRIPTION
**Pull request by evertramos**
Hello @bkzl ,

I think this was what you meant, right?

### CODE REVIEW

**Comment by bkzl** [comment]
Not really. In your implementation the value of `on` property doesn't really matter because `isActive` is always set by the event bindings anyway. So, you won't be able to disable floating label for specific condition.

**Comment by evertramos** [comment]
Well the idea was not to disable, but to load for a specific condition, so as far as I tested it, I could not make it work using on with true as default and along side (&&) with isActive, but ok, I will keep my version whish is working. Thanks

**Comment by evertramos** [comment]
I understand what you meant, and make sense. I just thought a little different... I do not use `<float-label>`in every `<input>` or `<select>`.... I have my own `<m-input>` where I implemented the float-label, so I could have a more clean code and a standard input tag. So this is might I look to the result a little different. 

Thanks!

**Comment by bkzl** [comment]
@evertramos Could you provide me some code examples? I would like to support your case too. ;)

**Pull request closed without merging**
